[workspace]
members = [
    "inet",
    "inet-bgp",
    "inet-rip",
    "inet-pcap",
    "inet-types",
    "inet-dns",
    "bytepack",
    "examples/*",
]

[patch.crates-io]
# des = { git = "https://github.com/PetrichorIT/des", branch = "beta"}
des = { path = "../des/des" }
