[package]
edition = "2021"
name = "inet"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "inet-bin"
path = "inet-bin/main.rs"

[[bin]]
name = "ideal-bin"
path = "ideal_bin/main.rs"

[[bin]]
name = "dns-tcp-bin"
path = "dns-tcp-bin/main.rs"

[dependencies]
async-trait = "*"
bytestream = "0.4"
# des = {git = "https://github.com/PetrichorIT/des", branch = "master", features = ["full"]}
des = {path = "../des/des", features = ["full"]}
log = {version = "*", features = ["max_level_trace"]}

[dev-dependencies]
serial_test = "1.0.0"
