[profile.release]
debug = true

[workspace]
members = [
    "inet",
    "inet-bgp",
    "inet-rip",
    "inet-pcap",
    "inet-dns",
    "inet-uds",
    "util/*",
    "examples/*",
]

[patch.crates-io]
# des = { git = "https://github.com/PetrichorIT/des", branch = "master" }
des = { path = "../des/des" }
