[package]
edition = "2021"
name = "inet"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "inet-bin"
path = "bin/main.rs"

[dependencies]
async-trait = "*"
bytestream = "0.4"
des = {git = "https://github.com/PetrichorIT/des", branch = "llcqueue-nightly", features = ["full"]}
log = {version = "*", features = ["max_level_trace"]}
tokio = {git = "https://github.com/PetrichorIT/tokio_sim", features = ["sim"]}
