[profile.release]
debug = true

[profile.test]
incremental = true
opt-level = 0
debug = 1
lto = false
debug-assertions = true
overflow-checks = true
rpath = false

[workspace]
members = [
    "inet",
    "inet-bgp",
    "inet-rip",
    "inet-pcap",
    "inet-dns",
    "inet-uds",
    "util/*",
    "examples/*",
    "inet-ospf",
]
resolver = "3"

[patch.crates-io]
# des = { git = "https://github.com/PetrichorIT/des", branch = "master" }
des = { path = "../des/des" }
