[package]
name = "dns-tcp-network"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inet = { path = "../../"} 
des = "*"
async-trait = "*"
log = { version = "*", features = ["max_level_info"]}