[package]
name = "inet-rip"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inet = { path = "../inet" }
bytes-io = { path = "../util/bytes-io" }
macros = { path = "../util/macros" }
fxhash = "*"
des = "*"
tracing = "*"
tokio = "*"

[dev-dependencies]
serial_test = "*"
serde_yml = "*"
pcapng = { path = "../util/pcapng" }
rand = "*"
des-ndl = "*"
