[package]
name = "inet-rip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inet = { path = "../inet"}
bytepack = { path = "../bytepack"}
fxhash = "*"
des = "*"
tracing = "*"
tokio = "*"