[package]
name = "inet-types"
version = "0.1.0"
edition = "2021"

[features]
default = []
dns = []
uds = []

[dependencies]
bytepack = { path = "../bytepack"}
des = { version = "*", features = ["full"] }