[package]
edition = "2024"
name = "inet"
version = "0.1.0"

[features]
full = ["dhcp"]

props = []
default = []
dhcp = []
libpcap = []
test-util = []


[dependencies]
async-trait = "*"
fxhash = "0.2.1"
des = { version = "*", features = ["full"] }
tokio = "1.37.0"
tracing = { version = "*" }
rand = "*"
types = { path = "../util/types" }
bytes-io = { path = "../util/bytes-io" }
bitflags = ">2.6.0"
serde = { version = "1.0", features = ["derive"] }
valuable = { git = "https://github.com/PetrichorIT/valuable", branch = "owned", features = [
    "derive",
] }
des-ndl = "*"


[dev-dependencies]
serial_test = "2.0.0"
serde_norway = "*"
pcapng = { path = "../util/pcapng", features = ["test-util"] }
