[package]
name = "types"
version = "0.1.0"
edition = "2021"

[features]
default = []
uds = []

[dependencies]
bitflags = "*"
bytepack = { path = "../bytepack" }
des = { version = "*", features = ["full"] }
