[package]
name = "types"
version = "0.1.0"
edition = "2021"

[features]
default = []
uds = []

[dependencies]
serde = { version = "*" }
bitflags = ">2.6.0"
bytes-io = { path = "../bytes-io" }
macros = { path = "../macros" }
des = { version = "*", features = ["full"] }
valuable = { git = "https://github.com/PetrichorIT/valuable", branch = "owned", features = [
    "derive",
] }

[dev-dependencies]
rand = "*"
